import type { Metadata } from "next";
import Link from "next/link";

import { routes } from "@/shared/config/routes";
import { PublicLayout } from "@/widgets/landing/public-layout";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Read the Orki Terms & Conditions governing your use of the platform, subscriptions, and board exam preparation services.",
};

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: [
      "By accessing or using Orki (\"the Platform\"), you agree to be bound by these Terms & Conditions. If you do not agree, please discontinue use immediately.",
      "These terms apply to all visitors, registered users, and subscribers of Orki, operated by the Orki Team.",
    ],
  },
  {
    id: "service",
    title: "2. Description of Service",
    content: [
      "Orki is a board exam preparation platform designed for Filipino professionals. The Platform provides mock examinations sourced from PRC materials and reputable online review resources, a flashcard system, analytics dashboards, and AI-powered personalized study recommendations for licensure examinations including PmLE, LET, CLE, and the Civil Service Examination.",
      "We reserve the right to modify, suspend, or discontinue any part of the Service at any time without prior notice.",
    ],
  },
  {
    id: "accounts",
    title: "3. Accounts & Registration",
    content: [
      "You may register using your email address or through Google Sign-In powered by Firebase Authentication. By using Google Sign-In, you authorize Orki to access your basic Google profile information (name and email address) solely for account creation and identification purposes.",
      "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized use at support@orki.cosedevs.com.",
      "You must be at least 18 years old or have parental consent to use this Platform.",
    ],
  },
  {
    id: "payments",
    title: "4. Subscriptions & Payments",
    content: [
      "Orki offers subscription plans that grant access to premium features. All payments are processed securely through PayMongo, a PCI-DSS compliant payment gateway licensed by the Bangko Sentral ng Pilipinas.",
      "By subscribing, you authorize Orki to charge your chosen payment method for the applicable subscription fee. Prices are listed in Philippine Peso (₱) and are inclusive of applicable taxes.",
      "Subscriptions automatically renew at the end of each billing period unless cancelled before the renewal date. You can manage your subscription from your account settings.",
      "Orki does not store your full payment card details. All sensitive payment data is handled exclusively by PayMongo.",
    ],
  },
  {
    id: "ai-content",
    title: "5. AI & Content Sourcing",
    content: [
      "Exam questions and flashcard content on Orki are sourced from PRC licensure examination materials and reputable online review resources. These are not generated by artificial intelligence.",
      "AI is used on the Platform exclusively for analytics, performance insights, and personalized study recommendations based on your individual results and progress.",
      "Content provided by the Platform is for educational and examination preparation purposes only. Orki does not guarantee that use of the Platform will result in passing any licensure examination.",
    ],
  },
  {
    id: "data",
    title: "6. User Data & Firebase",
    content: [
      "User data, including study progress, exam results, and flashcard activity, is stored in Google Firebase Firestore. By using the Platform, you consent to your data being processed and stored in Firebase's cloud infrastructure.",
      "We use Firebase services including Firebase Authentication, Cloud Firestore, and Firebase Analytics. Google's Privacy Policy governs the use of these underlying services.",
      "You may request deletion of your account and associated data at any time by contacting us at support@orki.cosedevs.com.",
    ],
  },
  {
    id: "conduct",
    title: "7. Prohibited Activities",
    content: [
      "You agree not to: (a) share, redistribute, or resell exam content; (b) use automated tools to scrape or harvest data from the Platform; (c) attempt to reverse-engineer any part of the Service; (d) impersonate another user or person; (e) use the Platform for any unlawful purpose.",
      "Violation of these prohibitions may result in immediate account termination without refund.",
    ],
  },
  {
    id: "ip",
    title: "8. Intellectual Property",
    content: [
      "All content on the Platform, including but not limited to questions, explanations, UI design, branding, and the Orki mascot, is the intellectual property of Orki and is protected by applicable Philippine and international copyright laws.",
      "You are granted a limited, non-exclusive, non-transferable license to use the Platform solely for personal, non-commercial examination preparation purposes.",
    ],
  },
  {
    id: "liability",
    title: "9. Limitation of Liability",
    content: [
      "To the maximum extent permitted by law, Orki and its team shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform.",
      "Our total liability to you for any claim shall not exceed the amount you paid to Orki in the three (3) months preceding the claim.",
    ],
  },
  {
    id: "governing-law",
    title: "10. Governing Law",
    content: [
      "These Terms shall be governed by the laws of the Republic of the Philippines. Any disputes arising shall be subject to the exclusive jurisdiction of the courts of the Philippines.",
    ],
  },
  {
    id: "changes",
    title: "11. Changes to These Terms",
    content: [
      "We may update these Terms from time to time. Material changes will be communicated via email or a prominent notice on the Platform. Continued use after changes constitutes acceptance of the revised Terms.",
    ],
  },
  {
    id: "contact",
    title: "12. Contact",
    content: [
      "If you have questions about these Terms, please contact us at support@orki.cosedevs.com.",
    ],
  },
];

export default function TermsPage() {
  return (
    <PublicLayout>
      {/* Hero */}
      <div className="bg-section-alt border-b border-border/50 py-14 sm:py-20 transition-colors duration-300">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <p className="text-xs font-bold uppercase tracking-widest text-primary mb-3">Legal</p>
          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-3 leading-tight">
            Terms &amp; Conditions
          </h1>
          <p className="text-muted text-sm">Last updated: May 24, 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-4xl px-4 sm:px-6 py-12 sm:py-16">
        {/* Quick navigation */}
        <div className="mb-10 p-5 rounded-2xl border border-border bg-card-bg transition-colors duration-300">
          <p className="text-xs font-bold uppercase tracking-widest text-muted mb-3">
            On this page
          </p>
          <div className="flex flex-wrap gap-2">
            {sections.map((s) => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="text-xs text-secondary hover:text-primary transition-colors"
              >
                {s.title}
              </a>
            ))}
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="scroll-mt-24">
              <h2 className="font-heading text-lg font-semibold text-foreground mb-3 pb-2 border-b border-border/50">
                {section.title}
              </h2>
              <div className="space-y-3">
                {section.content.map((para, i) => (
                  <p key={i} className="text-[15px] text-secondary leading-relaxed">
                    {para}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Footer CTA */}
        <div className="mt-12 pt-8 border-t border-border/50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <p className="text-sm text-muted">
            Questions about these terms?{" "}
            <Link href={routes.contact} className="text-primary hover:underline">
              Contact us
            </Link>
          </p>
          <div className="flex gap-3">
            <Link
              href={routes.privacy}
              className="text-sm text-secondary hover:text-primary transition-colors"
            >
              Privacy Policy →
            </Link>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
