# Generated by Django 5.2.7 on 2026-05-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_mockexam_examattempt_mockexamquestion_examanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexam',
            name='category',
            field=models.CharField(choices=[('CSE_PROF', 'CSE Professional'), ('CSE_SUBPROF', 'CSE Sub-Professional'), ('LET_GENED', 'LET General Education'), ('LET_PROFEDU', 'LET Professional Education'), ('PMLE_MAIN', 'Psychometricians Licensure Exam'), ('CLE_MAIN', 'Criminologist Licensure Exam')], max_length=30),
        ),
    ]
