# Generated by Django 6.0.5 on 2026-05-10 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='is_due',
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Ease factor (EF), min 1.3'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.PositiveIntegerField(default=0, help_text='Days until next review'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive correct recalls'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this card is due for review'),
        ),
    ]
