# Generated by Django 6.0.5 on 2026-05-13 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('LEPT', 'Licensure Examination for Professional Teachers'), ('CSE', 'Career Service Examination'), ('PmLE', 'Psychometricians Licensure Examination'), ('CLE', 'Criminologist Licensure Examination')], db_index=True, help_text='Short identifier used across the platform (e.g. LEPT, CSE)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full official name of the examination', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'db_table': 'catalog_exam_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'English'", max_length=255)),
                ('code', models.SlugField(help_text="URL-safe slug derived from name, e.g. 'english'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.examtype')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'catalog_subjects',
                'ordering': ['exam_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Grammar'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'catalog_topics',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, help_text='Original identifier from source JSON (e.g. ENG-001). Prevents duplicate imports.', max_length=50, unique=True)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField(blank=True, help_text='Optional — leave blank for true/false questions')),
                ('option_d', models.TextField(blank=True, help_text='Optional — leave blank for true/false questions')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='A, B, C, or D', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown to user after answering')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of string tags for search, filtering, and AI annotation')),
                ('source_file', models.CharField(blank=True, help_text='Relative path to the source JSON file (for traceability and re-import)', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'catalog_questions',
                'ordering': ['topic', 'source_id'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_type', 'code'], name='catalog_subject_type_code_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_type', 'is_active'], name='catalog_subject_type_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam_type', 'code')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'is_active'], name='catalog_topic_subject_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='catalog_q_topic_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'is_active'], name='catalog_q_topic_active_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'is_active'], name='catalog_q_diff_active_idx'),
        ),
    ]
