# Generated by Django 6.0.5 on 2026-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Target date for the actual exam', null=True),
        ),
    ]
