# Generated by Django 5.2.7 on 2026-05-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('LEPT', 'Licensure Examination for Professional Teachers'), ('CSE', 'Career Service Examination'), ('PmLE', 'Psychometricians Licensure Examination'), ('CLE', 'Criminologist Licensure Examination')], max_length=20),
        ),
    ]
