# Generated by Django 5.2.14 on 2026-05-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_subscription', 'No Subscription'), ('pending', 'Pending Verification'), ('subscriber', 'Active Subscriber')], default='no_subscription', max_length=20)),
                ('amount_php', models.DecimalField(decimal_places=2, default=49.0, max_digits=10)),
                ('paymongo_reference', models.CharField(blank=True, db_index=True, help_text='PayMongo checkout ID', max_length=255)),
                ('paymongo_payment_id', models.CharField(blank=True, help_text='PayMongo payment ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_initiated_at', models.DateTimeField(blank=True, help_text='When user initiated payment', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When admin verified payment', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.userprofile')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
