# Generated by Django 5.2.14 on 2026-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_initiated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paymongo_reference',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='When subscription expires (now + 30 days)', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_webhook_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Last webhook event ID processed (idempotency)', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When webhook confirmed payment', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('card', 'Credit/Debit Card'), ('qrph', 'QRPh'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paymongo_checkout_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayMongo checkout session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paymongo_reference_number',
            field=models.CharField(blank=True, help_text='PayMongo reference number for user communication', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(default='Orki Basic ₱49', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When subscription became active', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paymongo_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayMongo payment ID (source of truth)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('no_subscription', 'No Subscription'), ('active', 'Active Subscriber'), ('expired', 'Subscription Expired'), ('cancelled', 'Subscription Cancelled')], db_index=True, default='no_subscription', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['paymongo_payment_id'], name='subscriptio_paymong_f18e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['last_webhook_event_id'], name='subscriptio_last_we_6e36d6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expiry_date'], name='subscriptio_expiry__4b1c15_idx'),
        ),
    ]
