# Generated by Django 5.2.7 on 2026-05-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0003_alter_userprofile_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to='users.userprofile')),
            ],
            options={
                'db_table': 'daily_streaks',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('exam', 'Mock Exam'), ('flashcard', 'Flashcard Review'), ('quiz', 'Adaptive Quiz')], max_length=20)),
                ('exam_type', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='users.userprofile')),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('total_questions_attempted', models.PositiveIntegerField(default=0)),
                ('total_questions_correct', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_masteries', to='users.userprofile')),
            ],
            options={
                'db_table': 'subject_masteries',
                'ordering': ['-mastery_percentage'],
                'unique_together': {('user', 'exam_type', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TopicAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=150)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_accuracies', to='users.userprofile')),
            ],
            options={
                'db_table': 'topic_accuracies',
                'ordering': ['accuracy_percentage'],
                'unique_together': {('user', 'exam_type', 'subject', 'topic')},
            },
        ),
    ]
